### PR TITLE
Fixing the error with the message duplication.

### LINKED ISSUE #102: Incorrect date conversion for notifications
I am UTC-6, but I got this notification today:
```forhavu vs r-mena has been scheduled for 2016-07-06 @ 11:00 UTC, which is Wed @ 13:00 for you.```

Which is (for some reason) converting it it to UTC+2 !? I have tested locally and it's converting properly for me when testing locally. Note that the notification I got for my own game was also incorrect.

``` mooserohde vs lakinwecker has been scheduled for 2016-07-10 @ 20:00 UTC, which is Sun @ 22:00 for you.```

### PR DESCRIPTION
**Pull request by lakinwecker**
Fixes #102.   

Don't share the message between all of the callbacks. :)

### CODE REVIEW

**Comment by endrawes0** [comment]
Multi threading is fun

**Comment by endrawes0** [comment]
My understanding of the problem is: different execution contexts used the same instance of message and thus it was a race to see what the value was at the time the conversation was started.

**Comment by lakinwecker** [comment]
In this case, because it's async - there is no race.  The loop would finish completely and the last value of the message would be stored in that context. So all callbacks would use the last value of the message.

So yes, your understanding is correct generally, but because async is a bit more deterministic than threading, there is  a minor subtlety.

**Comment by endrawes0** [comment]
Thanks for the explanation.

**Pull request merged**
