### PR TITLE
add stalemate status to valid result scenarios

### PR DESCRIPTION
**Pull request by endrawes0**
addresses #49

### CODE REVIEW

**Comment by endrawes0** [comment]
Has not been tested, but w/e. Im a big boy. I will accept responsibility when it burns down the house.

**Comment by endrawes0** [comment]
OK - I need a recent game (in the last week). it has to be 30+30 or 45+45 and rated. Since a game cant be identified, we cannot test this.

Please just review closely (not much to see really, its a short one) and I will merge following.

Thanks

**Comment by endrawes0** [comment]
Tested by commenting out the check for round bounds.

**Comment by lakinwecker** [comment]
Looks good to me.

**Pull request merged**
