### PR TITLE
Adding jptriton fixing 110

### LINKED ISSUE #110: "Tell me when... " fails because "T"

### PR DESCRIPTION
**Pull request by lakinwecker**
Fixes #110 also add jptriton as a mod

### CODE REVIEW

**Comment by endrawes0** [comment]
Re-rubbing checks. Then will merge

**Comment by endrawes0** [comment]
Running* ha

**Comment by lakinwecker** [comment]
Looks like I need to update some code, I forgot to run the linting on it.

**Comment by endrawes0** [comment]
OK - just give me a heads up and Ill verify and merge.

**Comment by lakinwecker** [comment]
Done.

**Pull request merged**
