### PR TITLE
Removes changelog

### PR DESCRIPTION
**Pull request by aweidner**

### CODE REVIEW

**Comment by endrawes0** [comment]
Thanks for this. There is actually some code in Chesster that will also need cleaned up.

**Comment by endrawes0** [comment]
I was not suggesting you should do it - unless you wanted to. Just pointing it out.

**Comment by aweidner** [comment]
I think I got everything that needed to be removed from this, I merged it up with master too.  Is there anything else that needs to be done?

**Comment by lakinwecker** [comment]
I merged it with my long-standing branch. So it's actually merged with master via that branch

**Comment by lakinwecker** [comment]
Thanks!

**Pull request closed without merging**
