### PR TITLE
in single-purpose channels, ONLY use channel name for league detection.

### PR DESCRIPTION
**Pull request by lakinwecker**
This should fix the issue we've been seeing. I don't have all of the messages that where failing, but the ones that were failing were due to chesster thinking that the message text was identifying the lone wolf league as a target.  In the single-purpose channels, we don't want that. posts in #team-scheduling should always be considered a 45+45 message, regardless of content. 

This achieves that.

### CODE REVIEW

**Comment by lakinwecker** [comment]
I believe this closes #122

**Comment by endrawes0** [comment]
Makes sense to me. Will review when I'm fully awake

**Comment by endrawes0** [comment]
That middleware is proving to be as beautifully flexible as I had originally hoped.

**Comment by endrawes0** [comment]
Looks great. Thanks. 

I'm surprised we missed the pattern of games scheduled on the half hour.

**Pull request merged**
