### PR TITLE
reorganize the repo. needs to be tested throughly. 

### PR DESCRIPTION
**Pull request by endrawes0**
I have not tested this yet.

This is not meant to be merged yet. 

Just want to show reviewers the reorganization.

### CODE REVIEW

**Comment by endrawes0** [comment]
I dont expect checks to pass

**Comment by aweidner** [comment]
This looks good to me, it's a big improvement over what we currently have.

**Comment by lakinwecker** [comment]
I like the new organization. 

However, I think the Vagrantfile has to be at the top level as it 'mounts' your the directory that contains the Vagrantfile within the virtual machine - and that mount point needs access to the rest of the files.

**Comment by endrawes0** [comment]
Will update the location of the Vagrantfile.

**Comment by endrawes0** [comment]
left a debugger statement in.

**Comment by endrawes0** [comment]
Anyone have final comments before I merge?

**Comment by lakinwecker** [comment]
No final comments.

**Pull request merged**
